//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNETWAppCadFunc
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcionario
    {
        public int Id { get; set; }
        public string nome { get; set; }
        public string sobrenome { get; set; }
        public string email { get; set; }
        public string RG { get; set; }
        public string CPF { get; set; }
        public string logradouro { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string UF { get; set; }
        public int id_departamento { get; set; }
    
        public virtual tb_departamento tb_departamento { get; set; }
    }
}
